spring:
  profiles:
    active: dev
  application:
    name: Anime Service
  threads:
    virtual:
      enabled: true

server:
  servlet:
    context-path: "/anime-service/"
  error:
    include-stacktrace: on_param
  tomcat:
    threads:
      max: 20

database:
  mysql:
    url: localhost
    username: root
    password: root